spring:
  application:
    name: tech-challenge-03
  profiles:
    active: ${PROFILE:default}
  data:
    mongodb:
      uri: mongodb+srv://admin:${MONGODB_PASS}@my-cluster.jj29c.mongodb.net/techchallenge_03?retryWrites=true&w=majority

server:
  port: 8080
logging:
  level:
    root: INFO
    "[com.fiap.tech_challenge_03]": INFO
    "[org.springframework]": INFO
