spring:
  application:
    name: tech-challenge-03
  profiles:
    active: ${PROFILE:default}
server:
  port: 8080

logging:
  level:
    root: INFO
    "[com.fiap.tech_challenge_03]": INFO
    "[org.springframework]": INFO
